<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>	

		<!-- AssemblyInfo in Properties folder -->
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>	
		
		<!-- set restore source if needed. 
			Default to https://api.nuget.org/v3/index.json 
			https://apiint.nugettest.org/v3/index.json; for nuget sandbox 
		-->
		<RestoreSources>
			https://api.nuget.org/v3/index.json;
			https://apiint.nugettest.org/v3/index.json;
		</RestoreSources>

	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ScientiaMobile.Wurfl.Microservice.Client" Version="2.2.0"/>
	</ItemGroup>

</Project>
